### ISSUE TITLE
Python exception when using with Inkscape 0.92.2

### ISSUE THREAD

**Issue by FranzForstmayr** [fsmMLK/inkscapeCartesianAxes2D#3]
Hey,
i get following exception when using the script:

Traceback (most recent call last):
  File "cartesianAxes2D.py", line 89, in <module>
    axis.affect()
  File "C:\Program Files (x86)\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "cartesianAxes2D.py", line 84, in effect
    xGrid=so.xGrid, yGrid=so.yGrid, forceTextSize=textSize, forceLineWidth=lineWidthAxis)
  File "inkscapeMadeEasy_Plot.py", line 467, in cartesian
    inkDraw.text.latex(ExtensionBaseObj, groupTicks, xText, [posX + offsetX, axisOrigin[1] + offsetY], textSizeSmall, refPoint=justif)
  File "inkscapeMadeEasy_Draw.py", line 1232, in latex
    tex.affect([r'--text=' + LatexCommands + LaTeXtext, '--scale-factor=1', '--preamble-file=' + ExtensionBaseObj.getBasicLatexPackagesFile(), tempFilePath], output=False)
  File "C:\Program Files (x86)\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "textextLib/textext.py", line 363, in effect
    % ';\n'.join(converter_errors))
RuntimeError: No Latex -> SVG converter available:
PstoeditPlotSvg: Command pstoedit -help failed: [Error 2] Das System kann die angegebene Datei nicht finden;
SkConvert: Command pstoedit failed: [Error 2] Das System kann die angegebene Datei nicht finden;
Pdf2Svg: Command pdf2svg failed: [Error 2] Das System kann die angegebene Datei nicht finden

**Comment by chonuchan** [comment]
You need to install pdf2svg and poppler:

https://github.com/dawbarton/pdf2svg

**Comment by fsmMLK** [comment]
Please install package pstoedit and see if it fixes the problem.

**Comment by asadalam** [comment]
Similar error when trying to place a logic gate:
Traceback (most recent call last):
  File "logicGates.py", line 3, in <module>
    import inkex
  File "/usr/share/inkscape/extensions/inkex.py", line 114
    except Exception, e:
                    ^
SyntaxError: invalid syntax

package pstoedit is already installed. Inkscape version 0.91. Python version 3.7.0.

**Comment by Yklost** [comment]
Hi!

Firstly, thanks for this handy extension.
I've faced an issue, which I can't handle here. When I try to apply the cartesian axes, it throws this error:

/////////////////////////////////////////////////////////////////////////////////////////
Traceback (most recent call last):
  File "cartesianAxes2D.py", line 90, in <module>
    axis.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "cartesianAxes2D.py", line 85, in effect
    xGrid=so.xGrid, yGrid=so.yGrid, forceTextSize=textSize, forceLineWidth=lineWidthAxis)
  File "/usr/share/inkscape/extensions/inkscapeMadeEasy_Plot.py", line 544, in cartesian
    inkDraw.text.latex(ExtensionBaseObj, GroupAxis, xLabel, [xLimitsPos[1] + ExtraSpaceArrowX - text_offset / 3, axisOrigin[1] + text_offset / 2.0], textSize, refPoint='tl')
  File "/usr/share/inkscape/extensions/inkscapeMadeEasy_Draw.py", line 1259, in latex
    BboxMin, BboxMax = ExtensionBaseObj.getBoundingBox(groupLatex)
  File "/usr/share/inkscape/extensions/inkscapeMadeEasy_Base.py", line 860, in getBoundingBox
    coords = self.getPoints(element)
  File "/usr/share/inkscape/extensions/inkscapeMadeEasy_Base.py", line 826, in getPoints
    listPoints = self.getPoints(obj)
  File "/usr/share/inkscape/extensions/inkscapeMadeEasy_Base.py", line 826, in getPoints
    listPoints = self.getPoints(obj)
  File "/usr/share/inkscape/extensions/inkscapeMadeEasy_Base.py", line 833, in getPoints
    coordsNP = np.hstack((np.array(listCoords), np.ones([len(listCoords), 1]))).transpose()
  File "/usr/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 291, in hstack
    return _nx.concatenate(arrs, 0)
ValueError: all the input arrays must have same number of dimensions
///////////////////////////////////////////////////////////////////////////////////////////

I am using Inkscape 0.92.4 and Ubuntu 18.04.
Thanks for any help.

**Comment by dominikstaltner** [comment]
Hello,

I think that you have to install ghostscript additionally to pstoedit. For me this worked, but it could be that it makes a problem with pdf2svg so I uninstalled that. I'm a Windows 7 User.

Regards
