### ISSUE TITLE
Latex option error, ubuntu 16.04, inkscape 0.92

### ISSUE THREAD

**Issue by chonuchan** [fsmMLK/inkscapeCartesianAxes2D#4]
- InkscapeCartesianAxes2D and inkscapeMadeEasy are downloaded from Github repository.

- Textext is tested by calling from Inkscape toolbar, working fine.

- InkscapeCartesianAxes2D output correctly if Latex option is disabled in inkscapeMadeEasy_Draw by passing "useLatex=False".

- When using Latex option, the following error message returned:
Traceback (most recent call last):
  File "cartesianAxes2D.py", line 89, in <module>
    axis.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "cartesianAxes2D.py", line 84, in effect
    xGrid=so.xGrid, yGrid=so.yGrid, forceTextSize=textSize, forceLineWidth=lineWidthAxis)
  File "/home/hunter/.config/inkscape/extensions/inkscapeMadeEasy_Plot.py", line 467, in cartesian
    inkDraw.text.latex(ExtensionBaseObj, groupTicks, xText, [posX + offsetX, axisOrigin[1] + offsetY], textSizeSmall, refPoint=justif)
  File "/home/hunter/.config/inkscape/extensions/inkscapeMadeEasy_Draw.py", line 1259, in latex
    BboxMin, BboxMax = ExtensionBaseObj.getBoundingBox(groupLatex)
  File "/home/hunter/.config/inkscape/extensions/inkscapeMadeEasy_Base.py", line 613, in getBoundingBox
    coords = self.getPoints(element)
  File "/home/hunter/.config/inkscape/extensions/inkscapeMadeEasy_Base.py", line 573, in getPoints
    listPoints = self.getPoints(obj)
  File "/home/hunter/.config/inkscape/extensions/inkscapeMadeEasy_Base.py", line 573, in getPoints
    listPoints = self.getPoints(obj)
  File "/home/hunter/.config/inkscape/extensions/inkscapeMadeEasy_Base.py", line 586, in getPoints
    coordsNP = np.hstack((np.array(listCoords), np.ones([len(listCoords), 1]))).transpose()
  File "/usr/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 278, in hstack
    return _nx.concatenate(arrs, 0)
ValueError: all the input arrays must have same number of dimensions

- Checked with Inkscape debug output, it seems the root cause is in the following line:

coordsNP = np.hstack((np.array(listCoords), np.ones([len(listCoords), 1]))).transpose()

when Latex option is enabled, the "listCoords" variable passes an empty array and causing error in numpy.

when Latex option is disabled, the "listCoords" always passes [[0,0]].

- it is possible to bypass the error by adding the following if-condition before the line. However, the location of all texts are wrong. 

#if len(listCoords) == 0:
        #    listCoords = [[0,0]]

**Comment by fsmMLK** [comment]
It seems latex is not generating any text.

which ps->svg converter are you using? Try pstoedit

**Comment by chonuchan** [comment]
Thank you, installing pstoedit from the apt-get solved the issue.

I was using pdf2svg. While pdf2svg works well for Textext, it returns some empty elements, which caused the above-mentioned error.
